version: '3.3'

volumes:
  grocery_list-db:

services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - grocery_list-db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5434:5432'